# A 111M parameter Cerebras-GPT model configuration designed for a single CS-2

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir:
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/"
    shuffle: True
    shuffle_seed: 0
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 120 # 120 global = (120 micro)*(1 csx)*(1 grad accum step)
    num_workers: 1
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 120
    shuffle: False
    num_workers: 1


### Model
model:
    # Embedding
    hidden_size: 768
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048
    vocab_size: 50257

    # Decoder
    num_hidden_layers: 10
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training


    # Decoder - Attention
    num_heads: 12
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 3072
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Initializers
    embedding_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04
    initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.02
        a: -0.04
        b: 0.04
    output_layer_initializer:
        mean: 0.0
        name: truncated_normal
        std: 0.004472135954999579
        a: -0.008944271909999158
        b: 0.008944271909999158

    # Task-specific
    loss_scaling: "batch_size" # needed for gradient accumulation
    loss_weight: 0.00048828125 # = 1/max_sequence_length
    use_bias_in_output: False

    # Cerebras parameters
    mixed_precision: True
    fp16_type: "bfloat16"

### Optimization
optimizer:
    optimizer_type: "AdamW"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    max_gradient_norm: 1.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 0.0006
        total_iters: 1525
      - scheduler: "Linear"
        initial_learning_rate: 0.0006
        end_learning_rate: 6.0000e-05
        total_iters: 7512
    weight_decay: 0.1
    log_summaries: True
    correct_bias: True

### Cerebras parameters
runconfig:
    max_steps: 9037
    eval_steps: 1546
    checkpoint_steps: 903
    enable_distributed: False
    log_steps: 1
    save_initial_checkpoint: False
    precision_opt_level: 0 # also validated with precision_opt_level = 1
