#BERT-Base

### Input
train_input:
    data_processor: "QuestionAnsweringDataProcessor"
    data_file: "./squad/uncased_msl384_ds128_mql64/train.tf_record"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 384
    batch_size: 32
    shuffle: True

eval_input:
    data_processor: "QuestionAnsweringDataProcessor"
    data_file: "./squad/uncased_msl384_ds128_mql64/eval.tf_record"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 384
    batch_size: 32

predict_input:
    data_processor: "QuestionAnsweringDataProcessor"
    data_file: "./squad/uncased_msl384_ds128_mql64/predict.tf_record"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 384
    batch_size: 1

model:
    pretrain_params_path: "../../configs/params_bert_base_msl512.yaml"
    cls_dropout_rate: 0.1
    mixed_precision: True
    boundary_casting: False
    tf_summary: False

### Optimization
optimizer:
    optimizer_type: "adamw" # {"sgd", "momentum", "adam", "adamw"}
    weight_decay_rate: 0.01
    epsilon: 1e-6
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          steps: 1000
          initial_learning_rate: 0.0
          end_learning_rate: 0.00005
        - scheduler: "Constant"
          learning_rate: 0.00005
    loss_scaling_factor: "dynamic"

### Cerebras parameters
runconfig:
    max_steps: 10000
    save_summary_steps: 100
    save_checkpoints_steps: 1000
