#BERT-MNLI-Base

train_input:
    data_processor: "MNLIDataProcessor"
    data_dir: "./language/datasets/glue_data/MNLI"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 448
    batch_size: 16
    shuffle: True
    shuffle_seed: 1
    num_workers: 8
    do_lower: True

eval_input:
    data_processor: "MNLIDataProcessor"
    data_dir: "./language/datasets/glue_data/MNLI"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 448
    batch_size: 16
    shuffle: False
    shuffle_seed: 1
    num_workers: 1
    do_lower: True

model:
    mixed_precision: True
    vocab_size: 30522
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    task_dropout: 0.1
    problem_type: "single_label_classification"
    num_labels: 3
    compute_eval_metrics: True

optimizer:
    optimizer_type: "AdamW"
    weight_decay_rate: 0.01
    epsilon: 1e-6
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          steps: 7500
          initial_learning_rate: 0.0
          end_learning_rate: 0.00001
        - scheduler: "Constant"
          learning_rate: 0.00001
    loss_scaling_factor: "dynamic"
    log_summaries: True

runconfig:
    max_steps: 75000 # ~3 epochs, 372k samples in an epoch
    save_summary_steps: 100
    log_steps: 1000
    checkpoint_steps: 20000
    seed: 1
    show_debug_metrics: False
    save_losses: True
    model_dir: "./model_dir"
    save_initial_checkpoint: True
    eval_steps: 1226
