### Input
train_input:
    data_processor: "NerDataProcessor"
    data_dir: "./language/datasets/blurb/ner/bc5cdr-chem-pubmed_fulltext_uncased_vocab/bc5cdr-chem/train"
    vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    label_vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    max_sequence_length: 128
    max_predictions_per_seq: 20
    batch_size: 8
    shuffle: True

eval_input:
    data_processor: "NerDataProcessor"
    data_dir: "./language/datasets/blurb/ner/bc5cdr-chem-pubmed_fulltext_uncased_vocab/bc5cdr-chem/dev"
    vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    label_vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    max_sequence_length: 128
    max_predictions_per_seq: 20
    batch_size: 8
    shuffle: False

predict_input:
    # remaining params copied from eval_input
    # validation set needs to be a multiple of predict batch_size
    # or else data points will be dropped.
    data_processor: "NerDataProcessor"
    data_dir: "./language/datasets/blurb/ner/bc5cdr-chem-pubmed_fulltext_uncased_vocab/bc5cdr-chem/test"
    vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    label_vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    batch_size: 1

model:
    pretrain_params_path: "../../configs/params_bert_large_msl128.yaml"
    encoder_output_dropout_rate: 0.1
    num_classes: 7
    mixed_precision: True
    boundary_casting: False
    tf_summary: False
    include_padding_in_loss: False
    loss_weight: 0.04322062437752126  # 1/avg_num_tokens_in_sequence

### Optimization
optimizer:
    optimizer_type: "adam" # {"sgd", "momentum", "adam", "adamw"}
    epsilon: 1.e-6
    max_gradient_norm: 1.0
    disable_lr_steps_reset: True
    learning_rate:
        - scheduler: "Linear"
          steps: 1508  # 10% of max_steps
          initial_learning_rate: 0.0
          end_learning_rate: 0.00001
        - scheduler: "Linear"
          steps: 15080
          initial_learning_rate: 0.00001
          end_learning_rate: 0
    loss_scaling_factor: "dynamic"
    log_summaries: True

### Runtime config parameters
runconfig:
    max_steps: 15080 # 20 epochs
    eval_steps: 0 # eval_steps <= 0 means we use all of the eval data
    keep_checkpoint_max: 5
    enable_distributed: False
