##############################################################
## Base configuration: GPT-3 XL model (1.3B parameters)
##############################################################

train_input:
    data_processor: "GenomicDataProcessor"
    data_dir: "./anl_genomic/projects/RL-fold/sarscov2_filtered/train"
    vocab_file: "./anl_genomic/Gene_vocab_codon.txt"
    add_special_tokens: False
    batch_size: 33
    max_sequence_length: 10240
    shuffle: False  # Set this to False to make run deterministic
    vocab_size: 70
    n_gram: 3

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    max_sequence_length: 2048
    batch_size: 121
    shuffle: False
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

model:
    # Embedding
    vocab_size: 70
    hidden_size: 2048
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 10240

    # Decoder
    num_hidden_layers: 24
    dropout_rate: 0.1
    # https://huggingface.co/gpt2-xl/blob/main/config.json#L11 Since OpenAI did not share this setting
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training

    # Decoder - Attention
    num_heads: 16 # NOTE: Paper says "24" but was typo. Confirmed with authors
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.1
    # the following attention & ffn biases are set based on https://amaarora.github.io/2020/02/18/annotatedGPT2.html
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 8192 # 4 * hidden_size
    nonlinearity: "gelu"
    use_ffn_bias: True # As set in https://amaarora.github.io/2020/02/18/annotatedGPT2.html

    # Task-specific
    use_bias_in_output: False # As set in https://amaarora.github.io/2020/02/18/annotatedGPT2.html

    # Following TensorFlow which sets the bounds for truncated normal initialization to [-2*std, 2*std]
    # https://www.tensorflow.org/api_docs/python/tf/keras/initializers/TruncatedNormal
    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.002886751346 # 0.02 / sqrt(2 * num_hidden_layers)
        a: -0.005773502692
        b: 0.005773502692

    # Cerebras parameters
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    beta1: 0.9
    beta2: 0.95
    eps: 1.0e-8
    weight_decay_rate: 0.1
    max_gradient_norm: 1.0
    correct_bias: True
    learning_rate:
        - scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 1.0e-4 # sqrt(121 * 2048 / 1M) * 2.0e-4
          steps: 1500 # approx 375M tokens at batch size 121 and msl 2048
        - scheduler: "CosineDecay"
          initial_learning_rate: 1.0e-4
          end_learning_rate: 1.0e-5 # sqrt(121 * 2048 / 1M) * (0.1 * 2.0e-4)
          decay_steps: 1050000 # approx 260B tokens at batch size 121 and msl 2048
        - scheduler: "Constant"
          learning_rate: 1.0e-5

runconfig:
    max_steps: 5000 # GPT-3 models trained for approx 300B tokens
    log_steps: 10
    checkpoint_steps: 500
