# BERT-Base, MSL:384, SQuAD

train_input:
    data_processor: "BertQADataProcessor"
    data_dir: "./language/datasets/squad_csv/train/"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 384
    batch_size: 32
    shuffle: True
    shuffle_seed: 1
    num_workers: 2
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "BertQADataProcessor"
    data_dir: "./language/datasets/squad_csv/dev/"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 384
    batch_size: 32
    shuffle: True
    shuffle_seed: 1
    num_workers: 2
    prefetch_factor: 10
    persistent_workers: True

predict_input:
    data_processor: "BertQADataProcessor"
    data_dir: "./language/datasets/squad_csv/dev/"
    vocab_file: "../../../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 384
    batch_size: 1
    shuffle: True
    shuffle_seed: 1
    num_workers: 1
    prefetch_factor: 10
    persistent_workers: True

model:
    vocab_size: 30522
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu"
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    layer_norm_epsilon: 1.0e-5
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    epsilon: 1.0e-6
    weight_decay_rate: 0.01
    disable_lr_steps_reset: True
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.00005
         steps: 1000
       - scheduler: "Constant"
         learning_rate: 0.00005
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0

runconfig:
    max_steps: 10000
    log_steps: 100
    checkpoint_steps: 5000
    seed: 1
    show_debug_metrics: False
    save_losses: True
