# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# GPT-2 small model (117M parameters)
# Based on: https://huggingface.co/gpt2/resolve/main/config.json

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/language/datasets/owt_pretraining_gpt_hdf5/train_8M_msl2048"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 112
    shuffle: False  # Set this to False to make run deterministic
    shuffle_seed: 256
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/language/datasets/owt_pretraining_gpt_hdf5/val_msl2048"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 112 # 8, if run on 4 GPUs
    shuffle: False
    num_workers: 8


### Model
model:
    # Embedding
    hidden_size: 768
    vocab_size: 50257
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048

    # Encoder
    num_hidden_layers: 12
    dropout_rate: 0.1
    layer_norm_epsilon: 1.0e-5
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Encoder - Attention
    num_heads: 12
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.1
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Encoder - ffn
    filter_size: 3072
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    use_bias_in_output: False

    # Cerebras parameters
    mixed_precision: True

    fp16_type: "cbfloat16"

### Optimization
optimizer:
    optimizer_type: "adamw"
    betas: [0.9, 0.95]
    eps: 1.0e-8
    max_gradient_norm: 1.0
    learning_rate:
      ## GPT-3 schedule warms up over 375M tokens
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 0.0006
        total_iters: 1600
      ## GPT-3 schedule decays over 300B tokens, but we shorten
      ## to 34B (150k steps at BS=112)
      - scheduler: "Linear" # Cosine not supported
        initial_learning_rate: 0.0006
        end_learning_rate: 0.0
        total_iters: 150000
    weight_decay: 0.01
    initial_loss_scale: 2147483648.0
    max_loss_scale: 2147483648.0

    loss_scaling_factor: "dynamic"
### Cerebras parameters
runconfig:
    max_steps: 151600
    log_steps: 100
    checkpoint_steps: 10000
    save_initial_checkpoint: True
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 32

