# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# GPT-2 large model (774M parameters)

train_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/language/datasets/owt_pretraining_gpt_hdf5/train_8M_msl1024/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 32
    shuffle: False
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5MapDataProcessor"
    data_dir: "./shuffled/language/datasets/owt_pretraining_gpt_hdf5/val_msl1024/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 32
    shuffle: False
    num_workers: 8

model:
    # Embedding
    vocab_size: 50257
    hidden_size: 1280
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 1024

    # Encoder
    num_hidden_layers: 36
    dropout_rate: 0.1
    layer_norm_epsilon: 1.0e-5

    # Encoder - Attention
    num_heads: 20
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.1
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Encoder - ffn
    filter_size: 5120
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    use_bias_in_output: False
    loss_scaling: "num_tokens"
    loss_weight: 1.0

    # Cerebras parameters
    fp16_type: "cbfloat16"
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    correct_bias: True
    weight_decay: 0.01
    learning_rate: 0.0002
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 200000
    log_steps: 100
    checkpoint_steps: 10000
    seed: 1
    model_dir: "./model_dir"
    eval_steps: 233
