##############################################################
## Base configuration: GPT-3 13B model
##############################################################

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir:
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/0/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/1/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/2/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/3/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/4/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/5/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/6/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/7/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/8/"
        - "./language/datasets/pile_original/hdf5_dataset/train_shuffled_msl2048/9/"
    shuffle: True
    shuffle_seed: 0
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 1080 # 1080 global = (90 micro)*(num_csx)*(grad accum steps)
    num_workers: 1
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./language/datasets/pile_original/hdf5_dataset/val_msl2048/"
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 120
    shuffle: False
    num_workers: 1

### Model
model:
    # Embedding
    vocab_size: 50257
    hidden_size: 5120 # NOTE: Paper says "5140" but was typo. Confirmed with authors
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 2048

    # Decoder
    num_hidden_layers: 40
    dropout_rate: 0.0
    layer_norm_epsilon: 1.0e-5 # change to 1.0e-12 for single precision training

    # Decoder - Attention
    num_heads: 40
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.0
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Decoder - ffn
    filter_size: 20480 # 4 * hidden_size
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Initializers
    embedding_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.02
        a: -0.04
        b: 0.04

    output_layer_initializer:
        name: "truncated_normal"
        mean: 0.0
        std: 0.0025
        a: -0.005
        b: 0.005

    # Task-specific
    loss_scaling: "batch_size" # needed for gradient accumulation
    loss_weight: 0.00048828125 # = 1/max_sequence_length
    use_bias_in_output: False

    # Cerebras parameters
    mixed_precision: True
    use_bfloat16: True

### Optimization
optimizer:
    optimizer_type: "AdamW"
    beta1: 0.9
    beta2: 0.95
    eps: 1.0e-9
    max_gradient_norm: 1.0
    learning_rate:
      - scheduler: "Linear"
        initial_learning_rate: 0.0
        end_learning_rate: 0.00012
        steps: 169
      - scheduler: "CosineDecay"
        initial_learning_rate: 0.00012
        end_learning_rate: 1.2000e-05
        steps: 116054
    weight_decay_rate: 0.1
    log_summaries: True
    correct_bias: True

### Cerebras parameters
runconfig:
    max_steps: 116223
    eval_steps: 1507 # 180956 / 120
    checkpoint_steps: 500
    enable_distributed: False
    save_losses: True
    log_steps: 1
    save_initial_checkpoint: False
    use_cs_grad_accum: True
    use_appliance_data: True
    # Default optimizations level (POL=1) has not been tested for this model.
    # Convergence might be affected. POL=0 has been tested for convergence. To
    # use POL=0, uncomment this config:
    # precision_opt_level: 0
