# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# RoBERTa-Base, MSL:512

train_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "./language/datasets/wikicorpus_csv/train_cased_msl512_mlm_only_unmasked"
    vocab_file: "../../vocab/google_research_cased_L-12_H-768_A-12.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80
    shuffle: True
    shuffle_seed: 1
    do_lower: False
    batch_size: 256 # for GPU(16GB) set batch_size: 8
                    # 8 * 32 = 256 with grad_accum_steps: 32
    num_workers: 8

eval_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "./language/datasets/wikicorpus_csv/val_cased_msl512_mlm_only_unmasked"
    vocab_file: "../../vocab/google_research_cased_L-12_H-768_A-12.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80
    shuffle: False
    shuffle_seed: 1 # also for deterministic masking
    do_lower: False
    batch_size: 256 # for GPU(16GB) set batch_size: 8
    num_workers: 3

model:
    disable_nsp: True  # turn off NSP head
    vocab_size: 28996
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    mlm_loss_weight: 0.019 # should be 0.058 if training with max seq length 128, 0.019 with 512
    layer_norm_epsilon: 1.0e-5
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    correct_bias: True
    weight_decay_rate: 0.01
    disable_lr_steps_reset: True
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.0001
         steps: 10000
       - scheduler: "Linear"
         initial_learning_rate: 0.0001
         end_learning_rate: 0.0
         steps: 1000000
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0
#    grad_accum_steps: 32 # helps fit in GPU memory

runconfig:
    max_steps: 1000000
    log_steps: 100
    checkpoint_steps: 5000
    seed: 1
    model_dir: "./model_dir"
    show_debug_metrics: False
    save_losses: True
    save_initial_checkpoint: True
    eval_steps: 240
