# Copyright 2022 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#BERT-Base for Pfam
# Based on TAPE repos: https://github.com/songlab-cal/tape (pytorch) and
# https://github.com/songlab-cal/tape-neurips2019 (tensorflow).

### Input
train_input:
    data_dir: "./pfam/train"
    data_processor: PfamDataProcessor
    max_sequence_length: 700
    max_predictions_per_seq: 106
    shuffle: True
    shuffle_seed: 0
    repeat: True
    batch_size: 1024

eval_input:
    data_dir: "./pfam/val"
    data_processor: PfamDataProcessor
    max_sequence_length: 700
    max_predictions_per_seq: 106
    batch_size: 1024

model:
    disable_nsp: True
    # Embedding
    hidden_size: 768
    use_position_embedding: True
    use_segment_embedding: True
    position_embedding_type: "learned" # {"learned", "fixed"}
    max_position_embeddings: 700
    share_embedding_weights: True

    # Encoder
    num_hidden_layers: 12
    dropout_rate: 0.1
    layer_norm_epsilon: 1e-5

    # Encoder - Attention
    num_heads: 12
    attention_dropout_rate: 0.1

    # Encoder - ffn
    filter_size: 3072
    encoder_nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    mlm_loss_weight: 0.04194694809735963

    mixed_precision: True
    boundary_casting: False
    tf_summary: False


### Optimization
optimizer:
    optimizer_type: "adamw" # {"sgd", "momentum", "adam", "adamw"}
    weight_decay_rate: 0.01
    epsilon: 1e-6
    max_gradient_norm: 1.0
    beta_1: 0.9
    beta_2: 0.999
    learning_rate:
        - steps: 10000
          scheduler: "Linear"
          initial_learning_rate: 0.0
          end_learning_rate: 0.0001
        - scheduler: "Linear"
          initial_learning_rate: 0.0001
          end_learning_rate: 0.0
          steps: 290000
    loss_scaling_factor: "dynamic"

### Cerebras parameters
runconfig:
    max_steps: 300000
    save_summary_steps: 100
    save_checkpoints_steps: 1000
    keep_checkpoint_max: 0
    random_seed: 1202
    mixed_precision: True
    boundary_casting: False
    tf_summary: False
    enable_distributed: False
